set_property PACKAGE_PIN W7 [get_ports {segments[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[6]}]
set_property PACKAGE_PIN W6 [get_ports {segments[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[5]}]
set_property PACKAGE_PIN U8 [get_ports {segments[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[4]}]
set_property PACKAGE_PIN V8 [get_ports {segments[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[3]}]
set_property PACKAGE_PIN U5 [get_ports {segments[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[2]}]
set_property PACKAGE_PIN V5 [get_ports {segments[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[1]}]
set_property PACKAGE_PIN U7 [get_ports {segments[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[0]}]

set_property PACKAGE_PIN W4 [get_ports {anode_active[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode_active[3]}]
set_property PACKAGE_PIN V4 [get_ports {anode_active[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode_active[2]}]
set_property PACKAGE_PIN U4 [get_ports {anode_active[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode_active[1]}]
set_property PACKAGE_PIN U2 [get_ports {anode_active[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode_active[0]}]

set_property PACKAGE_PIN T17 [get_ports inputButtonRight]
set_property IOSTANDARD LVCMOS33 [get_ports inputButtonRight]

set_property PACKAGE_PIN W19 [get_ports inputButtonLeft]
set_property IOSTANDARD LVCMOS33 [get_ports inputButtonLeft]

set_property PACKAGE_PIN U18 [get_ports inputButtonCenter]
set_property IOSTANDARD LVCMOS33 [get_ports inputButtonCenter]

set_property PACKAGE_PIN W5 [get_ports inclk]
set_property IOSTANDARD LVCMOS33 [get_ports inclk]

set_property PACKAGE_PIN W13 [get_ports {inputMultiplier[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplier[7]}]
set_property PACKAGE_PIN W14 [get_ports {inputMultiplier[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplier[6]}]
set_property PACKAGE_PIN V15 [get_ports {inputMultiplier[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplier[5]}]
set_property PACKAGE_PIN W15 [get_ports {inputMultiplier[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplier[4]}]
set_property PACKAGE_PIN W17 [get_ports {inputMultiplier[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplier[3]}]
set_property PACKAGE_PIN W16 [get_ports {inputMultiplier[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplier[2]}]
set_property PACKAGE_PIN V16 [get_ports {inputMultiplier[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplier[1]}]
set_property PACKAGE_PIN V17 [get_ports {inputMultiplier[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplier[0]}]

set_property PACKAGE_PIN R2 [get_ports {inputMultiplicand[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplicand[7]}]
set_property PACKAGE_PIN T1 [get_ports {inputMultiplicand[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplicand[6]}]
set_property PACKAGE_PIN U1 [get_ports {inputMultiplicand[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplicand[5]}]
set_property PACKAGE_PIN W2 [get_ports {inputMultiplicand[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplicand[4]}]
set_property PACKAGE_PIN R3 [get_ports {inputMultiplicand[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplicand[3]}]
set_property PACKAGE_PIN T2 [get_ports {inputMultiplicand[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplicand[2]}]
set_property PACKAGE_PIN T3 [get_ports {inputMultiplicand[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplicand[1]}]
set_property PACKAGE_PIN V2 [get_ports {inputMultiplicand[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputMultiplicand[0]}]

set_property PACKAGE_PIN U16 [get_ports doneFlag]
set_property IOSTANDARD LVCMOS33 [get_ports doneFlag]